# Generated by Django 5.0.3 on 2024-03-11 07:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_fullname_signup_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
